### ISSUE TITLE
Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by AjayPoshak** [preactjs/wmr#206]
When I run `npm run build`, I get below error

```
> @ build /Users/ajayposhak/Projects/foo
> wmr build --prerender

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ajayposhak/Projects/foo/node_modules/wmr/wmr.cjs:2:266)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `wmr build --prerender`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajayposhak/.npm/_logs/2020-12-03T08_39_59_702Z-debug.log
```

Node version is `v10.16.3`, so I think minimum required version to use wmr should be node v15.

**Comment by AjayPoshak** [comment]
It goes away when I upgrade my node to version 15. I think it would be great to mention this in documentation and/or have a `engines` field in `package.json`. I'll be happy to open a PR for this.

**Comment by marvinhagemeister** [comment]
@AjayPoshak Yeah we only support Node >= 14. Adding the `engines` field sounds like a fantastic solution. Happy to merge a PR for this 👍

**Comment by lukeed** [comment]
What's the reason for 14? The `worker_threads` is 10+ and ESM is 12+, so I would have guessed 12

**Comment by marvinhagemeister** [comment]
During the beta phase we had weird issues with the ESM implementation in < 14. Can't remember what they were exactly anymore, but we couldn't figure those out back then.

**Comment by lukeed** [comment]
Ah. Well 12 has the same ESM impl as 14. You probably ran into issues with the 13.0-13.7 range, which has borked `exports` map support
