### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME

### ISSUE THREAD

**Issue by bahrus** [preactjs/wmr#207]
Looks promising!

OS:  Windows 10 Personal
Node version:  v15.3.0 64 bit
npm version:7.0.15

when I run:

>npm run build

I get the following output:

> build
> wmr build --prerender

Wrote 22Kb to disk:
  index.html 469b
  index.ba53af13.js 16Kb
  chunks/index.a7575811.js 225b
  chunks/prerender.e177af32.js 4.9Kb
  assets/style.e6ee4bcf.css 499b
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:278:15)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:825:11)
    at Loader.resolve (node:internal/modules/esm/loader:86:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:230:28)
    at Loader.import (node:internal/modules/esm/loader:165:28)
    at importModuleDynamically (node:internal/process/execution:83:29)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:448:15)
npm ERR! code 1
npm ERR! path C:\git\wmr\foo
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c wmr build --prerender

**Comment by crazy4groovy** [comment]
I'm still having this issue, new install today:

```
	"devDependencies": {
		"wmr": "^1.0.0"
	}
```

```
B:\dev\projects\_scrap\my-preact-wmr>npm run build

> @ build B:\dev\projects\_scrap\my-preact-wmr
> wmr build --prerender

(node:21284) ExperimentalWarning: The ESM module loader is experimental.
Wrote 22Kb to disk:
  index.html 469b
  index.ba53af13.js 16Kb
  chunks/index.a7575811.js 225b
  chunks/prerender.e177af32.js 4.9Kb
  assets/style.e6ee4bcf.css 499b
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:698:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at Loader.import (internal/modules/esm/loader.js:178:28)
    at importModuleDynamically ([worker eval]-wrapper:17:31)
    at async importModuleDynamicallyWrapper (internal/vm/module.js:432:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `wmr build --prerender`
npm ERR! Exit status 1
```

**Comment by crazy4groovy** [comment]
Fix may not be released yet?

**Comment by lukeed** [comment]
Yup, not published yet
