### ISSUE TITLE
Cannot import fontsource

### ISSUE THREAD

**Issue by gianpaj** [preactjs/wmr#232]
How would one go about importing `fontsource`?
https://github.com/fontsource/fontsource

https://fontsource.github.io/search-directory/#roboto

If I install the package and add the import I get this error:
`import 'fontsource-roboto';`

```
Error bundling fontsource-roboto:  Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
    at vr (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:85597)
    at Lo.error (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:166363)
    at To (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:164515)
    at Lo.setSource (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:171648)
    at lu.addModuleSource (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:316003)
    at async lu.fetchModule (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:317072)
    at async Promise.all (index 0) {
  code: 'PARSE_ERROR',
  parserError: SyntaxError: Unexpected character '@' (2:0)
      at Object.rc.raise (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:271192)
      at Object.Gc.getTokenFromCode (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:301759)
      at Object.getTokenFromCode (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:329944)
      at Object.Gc.readToken (/Users/gpalumbo/personal/confettillabs/node_modules/wmr/wmr.cjs:2:296154)
```

**Comment by rschristian** [comment]
Looks to be an issue with the CSS handling of all at-rules, and `fontsource` uses `@fontface`.

**Comment by developit** [comment]
Hmm - yeah honestly I'm not 100% sure where in the stack this is failing...

Another option that I believe would work is using the `css:` prefix:

```js
import 'css:fontsource-roboto';
```
