### ISSUE TITLE
UnhandledPromiseRejectionWarning when running wmr start >= 1.4.0

### ISSUE THREAD

**Issue by rschristian** [preactjs/wmr#499]
**Describe the bug**

When running `wmr start` in a brand new, untouched project, I'm met with the following warning: 

```
➜  ~/Projects/tmp git:(refactor/wmr) ✗ yarn start
yarn run v1.22.10
$ wmr

  👩‍🚀 WMR server running at:

  Local:   http://localhost:8080
  Network: http://192.168.100.128:8080

(node:78273) UnhandledPromiseRejectionWarning: TypeError: yUe.watch is not a function
    at YUe (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2323875)
    at ZUe (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2324290)
    at rJe._watchWithFsEvents (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2325997)
    at rJe.initWatch (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2327434)
    at rJe._addToFsEvents (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2328648)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:78273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:78273) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:78273) UnhandledPromiseRejectionWarning: TypeError: yUe.watch is not a function
    at YUe (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2323875)
    at ZUe (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2324290)
    at rJe._watchWithFsEvents (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2325997)
    at rJe.initWatch (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2327434)
    at rJe._addToFsEvents (/home/ryun/Projects/wmr/packages/wmr/wmr.cjs:2:2328648)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:78273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**To Reproduce**
1. `npm init wmr foo`
2. `npm run start`

**Expected behavior**

Warning should not appear

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: N/A
 - WMR Version: 1.4.0 and above seem to be affected
 - Node: 14.16.0

**Additional context**

This doesn't seem to have any effect beyond the console output that I've noticed.

Building and using locally still displays this problem.

**Comment by developit** [comment]
Can reproduce this on Node 15.20.0 / Mac / Arm64.
