### ISSUE TITLE
Quickstart instructions fail

### ISSUE THREAD

**Issue by lgarron** [preactjs/wmr#703]
**Describe the bug**

The quickstart instructions at https://github.com/preactjs/wmr#quickstart-recommended fail with an error.

**To Reproduce**

Run:

```shell
npm init wmr your-project-name
```

This results in:

```
d> npm init wmr your-project-name
Need to install the following packages:
  create-wmr
Ok to proceed? (y) y
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'string_decoder/'
Require stack:
- /Users/lgarron/.cache/npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/lgarron/.cache/npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js:2:194)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lgarron/.cache/npm/_npx/3c66316f091b0520/node_modules/create-wmr/dist/index.js'
  ]
}
npm ERR! code 1
npm ERR! path /Users/lgarron/Downloads/kjdsfd
npm ERR! command failed
npm ERR! command sh -c create-wmr "your-project-name"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lgarron/.cache/npm/_logs/2021-06-24T03_24_01_932Z-debug.log
```

`/Users/lgarron/.cache/npm/_logs/2021-06-24T03_24_01_932Z-debug.log` contains:

```shell
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/16.2.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'init',
0 verbose cli   'wmr',
0 verbose cli   'your-project-name'
0 verbose cli ]
1 info using npm@7.15.0
2 info using node@v16.2.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/lgarron/Downloads/kjdsfd/.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/lgarron/.config/npm/config Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 2ms
21 timing npm:load:setupLog Completed in 2ms
22 timing npm:load:cleanupLog Completed in 1ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 16ms
26 timing config:load:flatten Completed in 2ms
27 http fetch GET 304 https://registry.npmjs.org/create-wmr 178ms (from cache)
28 timing arborist:ctor Completed in 1ms
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 0ms
31 timing idealTree:init Completed in 8ms
32 timing idealTree:userRequests Completed in 1ms
33 silly idealTree buildDeps
34 silly fetch manifest create-wmr@^0.1.4
35 http fetch GET 200 https://registry.npmjs.org/create-wmr 3ms (from cache)
36 silly placeDep ROOT create-wmr@0.1.4 KEEP for:  want: ^0.1.4
37 timing idealTree:#root Completed in 9ms
38 timing idealTree:buildDeps Completed in 9ms
39 timing idealTree:fixDepFlags Completed in 0ms
40 timing idealTree Completed in 21ms
41 timing reify:loadTrees Completed in 21ms
42 timing reify:diffTrees Completed in 1ms
43 silly reify moves {}
44 timing reify:retireShallow Completed in 0ms
45 timing reify:createSparse Completed in 0ms
46 timing reify:loadBundles Completed in 0ms
47 silly audit bulk request { 'create-wmr': [ '0.1.4' ] }
48 timing reify:unpack Completed in 0ms
49 timing reify:unretire Completed in 0ms
50 timing build:queue Completed in 0ms
51 timing build:deps Completed in 1ms
52 timing build Completed in 1ms
53 timing reify:build Completed in 1ms
54 timing reify:trash Completed in 0ms
55 timing reify:save Completed in 5ms
56 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 167ms
57 timing auditReport:getReport Completed in 168ms
58 silly audit report {}
59 timing auditReport:init Completed in 0ms
60 timing reify:audit Completed in 169ms
61 timing reify Completed in 195ms
62 timing command:init Completed in 2022ms
63 verbose stack Error: command failed
63 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
63 verbose stack     at ChildProcess.emit (node:events:365:28)
63 verbose stack     at maybeClose (node:internal/child_process:1067:16)
63 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
64 verbose cwd /Users/lgarron/Downloads/kjdsfd
65 verbose Darwin 20.5.0
66 verbose argv "/usr/local/Cellar/node/16.2.0/bin/node" "/usr/local/bin/npm" "init" "wmr" "your-project-name"
67 verbose node v16.2.0
68 verbose npm  v7.15.0
69 error code 1
70 error path /Users/lgarron/Downloads/kjdsfd
71 error command failed
72 error command sh -c create-wmr "your-project-name"
73 verbose exit 1
```

**Expected behavior**

Project creation succeeds.

**Desktop (please complete the following information):**

npm 7.15.0
node v16.2.0
macOS 11.4

**Comment by rschristian** [comment]
Same issue as #506 it looks like. Try running `npm init wmr your-project-name --prefer-online`.

`create-wmr` (the package used for initalization) is currently on [v0.3.7](https://github.com/preactjs/wmr/releases/tag/create-wmr%400.3.7) but it looks like you're using v0.1.4. Probably a cache issue.

You could also run `npm init wmr@0.3.7 your-project-name` to force it to use the newer version, though I'm not sure if that'll update the cache.

**Comment by lgarron** [comment]
> Same issue as #506 it looks like. Try running `npm init wmr your-project-name --prefer-online`.

Hmm, that runs into the same error. :-(

I tried `npm uninstall -g wmr` to see if that would help, but it didn't.

> You could also run `npm init wmr@0.3.7 your-project-name` to force it to use the newer version, though I'm not sure if that'll update the cache.

This does!

**Comment by lgarron** [comment]
Well, this was not an ideal experience, but I was able to set up a project and confirm compatibility with some worker code that has been a pain for other bundlers (e.g. https://github.com/snowpackjs/snowpack/issues/3476). :-D

**Comment by rschristian** [comment]
It does update the cache? As in, `npm init wmr` now works, or only if you use the version as well?

**Comment by lgarron** [comment]
> It does update the cache? As in, `npm init wmr` now works, or only if you use the version as well?

Only if I use the version. 🤷‍♀️

**Comment by rschristian** [comment]
Ah. Well, maybe `npm cache clean`? Not really sure what else it could be. While this was a valid issue, it was solved months ago. NPM's CLI just keeps handing out super outdated versions.

**Comment by lgarron** [comment]
For the record, I think I finally fixed this by blowing away `node`, `npm`, and every path that somewhere on the internet said was related to one of them (config, cache, data, etc.). And then reinstalling from scratch.
