### ISSUE TITLE
TypeScript 4.3 `override` keyword 

### ISSUE THREAD

**Issue by lgarron** [preactjs/wmr#714]
**Describe the bug**

Using the `override` keyword in `.ts` files seems to break `wmr`.

**To Reproduce**

Add this code to e.g. the default template:

```js
class A {
  hi() {}
}

class B extends A {
  override hi() { console.log("yo"); }
}

new B().hi();
```

This results in:

```
500 ./public/index.ts - Error transforming ./index.ts: Unexpected token (13:12)

  11 | 
  12 | class B extends A {
> 13 |   override hi() {
     |             ^
  14 |     console.log("yo");
  15 |   }
  16 | }

  at Pb (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:977734)
  at AO (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1088756)
  at gO (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1088389)
  at mO (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1088063)
  at dO (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1087643)
  at Rk (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1083846)
  at Lk (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1083534)
  at aO (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1086548)
  at Fk (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1083310)
  at UO (/Users/lgarron/Downloads/wmr-test/node_modules/wmr/wmr.cjs:2:1091661)
```

**Expected behavior**

The code works? 😃

**Desktop (please complete the following information):**

npm 7.15.0
node v16.2.0
macOS 11.4
wmr 3.1.0

**Additional context**

I filed an issue about private method support and mentioned private methods as an important compatibility for our project: https://github.com/preactjs/wmr/issues/708#issuecomment-868364225
We'd also love to use [the `override` keyword from TypeScript 4.3.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag), which has been previously blocked by lack of support in other bundlers. I don't know much about `acorn`, but as far as I know it's safe to simply strip the keyword out when types are not being checked.

**Comment by marvinhagemeister** [comment]
Currently, using `sucrase` to strip TypeScript types and turn it into JavaScript. It looks like the error is coming from there. Filed an upstream issue: https://github.com/alangpierce/sucrase/issues/629
