### ISSUE TITLE
The type of the request and response objects middlewares are called with are wrong

### ISSUE THREAD

**Issue by fabiospampinato** [preactjs/wmr#748]
**Describe the bug**

I'm being told by the types that `res.redirect` exists for example:

<img width="786" alt="Screen Shot 2021-07-08 at 19 07 40" src="https://user-images.githubusercontent.com/1812093/124970440-cf369180-e01f-11eb-9c07-435efa66fbb3.png">

While in fact it doesn't and having that code produces the following error:

```
TypeError: res.redirect is not a function

    at Array.defineConfig.middleware (file:///Users/fabio/Desktop/root-wmr/wmr.config.mjs?t=1625767556779:21:13)
    at u (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2743901)
    at l (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2743869)
    at Array.<anonymous> (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2892824)
    at u (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2743901)
    at l (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2743869)
    at Array.<anonymous> (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2759991)
    at u (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2743901)
    at o8e.handler (/Users/fabio/Desktop/root-wmr/node_modules/wmr/wmr.cjs:2:2743928)
    at Server.emit (events.js:314:20)
```

**Expected behavior**

Types should be correct.

**Desktop (please complete the following information):**

- WMR Version: 3.3.1

**Comment by developit** [comment]
This is a bug in Polka's TypeScript definition, which is provided by DefinitelyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/polka/index.d.ts#L10

(it's incorrectly using the decorated Response from `express`, despite Polka providing only the Node core Response object).

**Comment by marvinhagemeister** [comment]
Filed an upstream PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54390

**Comment by developit** [comment]
Interestingly, we have our own (correct) type definition for this internally:
https://github.com/preactjs/wmr/blob/bd43ba063e34eedacdb15458961d578697a69258/packages/wmr/src/server.js#L14-L17

Maybe we should switch from the Polka definitions to our own? IIRC it's the only external type definition we rely on, which makes compiling `.d.ts` a pain.
