### ISSUE TITLE
404 /@npm/@npm/[package-name] - npm registry lookup failed

### ISSUE THREAD

**Issue by rejhgadellaa** [preactjs/wmr#903]
**Describe the bug**

When running wmr in dev/watch mode I often get the following error when I try to view the page in my browser:

```
404 /@npm/@npm/[package-name] - npm registry lookup failed for "@npm/[package-name]": Package doesn't exist.
```

The error is not very consistent, sometimes the page loads but at least ~50% of the time I see the error and I have to exit, delete the `.cache` folder and restart wmr and hope it works.

It's not very consistent with which package it can't find, either. Most of the time it's one package, sometimes multiple. So far, I think I've only seen the following packages not being found:

* object-assign
* react-is

The packages in question are present in the `node_modules` folder. I checked the `.cache/@npm` folder, and if the error occurs, the packages are missing there, so it seems wmr (silently) fails to cache the package?

This issue makes working with wmr pretty impossible for me :(

Note: Not entirely sure if deleting the `.cache` folder is required but from my observations so far, restarting wmr without deleting the `.cache` folder just causes the same error with the same package every time I reload the page. When I do delete the cache folder, it either works or I get another 404 but not always the same package.

**To Reproduce**

1. Cd into a project, run `npm start`
2. Open a browser and navigate to `localhost:8080`
3. Observe wmr for 404 errors

**Expected behavior**

I expect no 404 errors

**Bug occurs with:**

- [x] `wmr` or `wmr start` (development)
- [ ] `wmr build` (production)
- [ ] `wmr serve`

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Node Version: 16.13.1
- WMR Version: ^3.7.2

**Additional context**

#882 covers the same issue but has been closed by the reporter without a clear description of the cause and/or how to fix it. Another user reported he's (also) seeing this issue with the `filter-obj` package.

This problem occurs whether I run wmr via PowerShell or a Ubuntu terminal (WSL 1.x). Note: I do run the WSL terminal in the same (windows mounted) folder, so `/mnt/c/path/to/project`.

**Comment by rejhgadellaa** [comment]
For completeness, here's a full output when I run `npm start` and try to load it in the browser:

```
> project@0.0.0 start
> rimraf .cache && wmr

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

  👩‍🚀 WMR dev server running at:

  Local:   http://localhost:8080
  Network: (disabled, see --host)


404 /@npm/@npm/react-is - npm registry lookup failed for "@npm/react-is": Package doesn't exist.

  at TT (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:1194284)
  at  (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:1239595)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async KR (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:1239205)
  at async HR (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:1239084)
  at async Array.<anonymous> (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:2934077)

404 /@npm/@npm/object-assign - npm registry lookup failed for "@npm/object-assign": Package doesn't exist.

  at TT (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:1194284)
  at  (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:1239595)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async KR (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:1239205)
  at async HR (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:1239084)
  at async Array.<anonymous> (/mnt/c/path/to/project/node_modules/wmr/wmr.cjs:2:2934077)
```

**Comment by Aloento** [comment]
maybe same with https://github.com/preactjs/wmr/issues/919
